springBootVersion=4.0.3
springDependencyManagementVersion=1.1.7

clickHouseJdbc=0.9.8

lz4JavaVersion=1.8.1

lombokVersion=9.5.0

mapstructVersion=1.6.3

avroVersion=1.12.1
avroGeneratorPluginVersion=1.9.1
schemaRegistryClientVersion=8.2.1

uuidv7Version=1.0.1

flywayVersion=12.9.0

hypersistenceUtilsVersion=3.15.4