# Настройки подключения
listen_addresses = '*'
port = 5432

# Настройки репликации
wal_level = replica
max_wal_senders = 10
wal_keep_size = 128MB
hot_standby = on

# Указываем путь к pg_hba.conf
hba_file = '/etc/postgresql/pg_hba.conf'