version: '2'

services:
    kafka:
        image: apache/kafka:4.2.0
        container_name: sc-kafka
        environment:
            # Переменные для запуска Kafka в режиме KRaft
            KAFKA_NODE_ID: 1
            KAFKA_PROCESS_ROLES: broker,controller
            KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
            KAFKA_NUM_PARTITIONS: '12'
            KAFKA_COMPRESSION_TYPE: 'gzip'
            KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:19092
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:19092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
            KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_LOG_DIRS: /var/lib/kafka/data
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

        hostname: kafka
        ports:
            - "9092:9092"
            - "9093:9093"
            - "19092:19092"
        healthcheck:
            test: ["CMD-SHELL", "nc -vz localhost 9092"]
            interval: 15s
            timeout: 5s
            retries: 10

    schema-registry:
        image: confluentinc/cp-schema-registry:8.2.0
        container_name: sc-schema-registry
        hostname: schema-registry
        depends_on:
            - kafka
        environment:
            SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
            SCHEMA_REGISTRY_HOST_NAME: schema-registry
            SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8381
            SCHEMA_REGISTRY_KAFKASTORE_TOPIC: _schemas
            SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: INFO
        ports:
            - 8381:8381
        healthcheck:
            test: [ "CMD-SHELL", "curl -f http://localhost:8381/subjects" ]
            interval: 15s
            timeout: 5s
            retries: 10

    clickhouse:
        image: clickhouse/clickhouse-server:26.2
        container_name: sc-clickhouse
        ports:
            - "8123:8123"
            - "9000:9000"

        environment:
            CLICKHOUSE_DB: iot_platform
            CLICKHOUSE_USER: ${CLICKHOUSE_USER}
            CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
            CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
        healthcheck:
            test: [ "CMD-SHELL", "clickhouse-client --query 'SELECT 1'" ]
            interval: 15s
            timeout: 5s
            retries: 10


    redis:
        image: redis:8.6.3-alpine
        container_name: redis
        ports:
            - "6379:6379"
        environment:
            REDIS_PASSWORD: ${REDIS_PASSWORD}
        command: >
            redis-server
            --save 60 1
            --loglevel warning
            --requirepass ${REDIS_PASSWORD}
        restart: unless-stopped
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            interval: 15s
            timeout: 5s
            retries: 10

    # ---- Первый шард PostgreSQL ----
    postgres-shard1:
        image: postgres:18-alpine
        container_name: postgres-shard1
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes:
            - ./config/postgresql/init-scripts:/docker-entrypoint-initdb.d/
        ports:
            - "5433:5432"
        restart: unless-stopped
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
            interval: 10s
            timeout: 5s
            retries: 5

    # ---- Второй шард PostgreSQL ----
    postgres-shard2:
        image: postgres:18-alpine
        container_name: postgres-shard2
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes:
            - ./config/postgresql/init-scripts:/docker-entrypoint-initdb.d/
        ports:
            - "5434:5432"
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
            interval: 10s
            timeout: 5s
            retries: 5

    # ---- ShardingSphere-Proxy ----
    shardingsphere-proxy:
        image: apache/shardingsphere-proxy:5.5.3
        container_name: shardingsphere-proxy
        ports:
            - "13308:3308"  # Прокси будет доступен на порту 13308
        volumes:
            - ./global.yaml:/opt/shardingsphere-proxy/conf/global.yaml
            - ./config-sharding.yaml:/opt/shardingsphere-proxy/conf/config-sharding.yaml
        environment:
            PORT: 3308
            JVM_OPTS: "-Djava.awt.headless=true"
        healthcheck:
            test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/localhost/3308' && echo 'OK' || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 5
        depends_on:
            postgres-shard1:
                condition: service_healthy
            postgres-shard2:
                condition: service_healthy
        restart: unless-stopped

    kafka-ui:
        container_name: shcut-kafka-ui
        image: provectuslabs/kafka-ui:v0.7.2
        ports:
            - 9999:8080
        depends_on:
            - kafka
            - schema-registry
        environment:
            DYNAMIC_CONFIG_ENABLED: true
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
            KAFKA_CLUSTERS_0_SCHEMAREGISTRY: "http://schema-registry:8381"

    # ---- Мои сервисы ----
    events-collector-service:
        build:
            context: ../events-collector-service
            dockerfile: Dockerfile
        container_name: events-collector-service
        environment:
            SPRING_PROFILES_ACTIVE: docker
            CLICKHOUSE_USER: ${CLICKHOUSE_USER}
            CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
            REDIS_PASSWORD: ${REDIS_PASSWORD}
        depends_on:
            clickhouse:
                condition: service_healthy
            redis:
                condition: service_healthy
            kafka:
                condition: service_healthy
            schema-registry:
                condition: service_healthy
        restart: unless-stopped
        labels:
            logging: "promtail"
        expose:
            - "8780"
            - "8781"
        ports:
            - 8780:8780
            - 8781:8781

    device-collector-service:
        build:
            context: ../device-collector-service
            dockerfile: Dockerfile
        container_name: device-collector-service
        environment:
            SPRING_PROFILES_ACTIVE: docker
            CLICKHOUSE_USER: ${CLICKHOUSE_USER}
            DEVICE_COLLECTOR_PR_PG_USER: ${DEVICE_COLLECTOR_PR_PG_USER}
            DEVICE_COLLECTOR_PR_PG_PASSWORD: ${DEVICE_COLLECTOR_PR_PG_USER}
        depends_on:
            kafka:
                condition: service_healthy
            schema-registry:
                condition: service_healthy
            shardingsphere-proxy:
                condition: service_healthy
        restart: unless-stopped
        labels:
            logging: "promtail"
        expose:
            - "8780"
            - "8791"
        ports:
            - 8790:8790
            - 8791:8791

    ## --- СЕРВИСЫ МОНИТОРИНГА  ---
    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
        ports:
            - "9090:9090"
        restart: unless-stopped

    loki:
        image: grafana/loki:latest
        container_name: loki
        ports:
            - "3100:3100"
        volumes:
            - ./loki-config.yaml:/etc/loki/loki-config.yaml:ro
        command: -config.file=/etc/loki/loki-config.yaml
        restart: unless-stopped

    alloy:
        image: grafana/alloy:latest
        container_name: alloy
        volumes:
            - ./config.alloy:/etc/alloy/config.alloy:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro  # для доступа к контейнерам (логи Docker)
            - /var/lib/docker/containers:/var/lib/docker/containers:ro  # файлы логов
        ports:
            - "12345:12345"   # внутренний HTTP-сервер Alloy для отладки
        command: run --server.http.listen-addr=0.0.0.0:12345 /etc/alloy/config.alloy
        restart: unless-stopped
        depends_on:
            - prometheus
            - loki

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        ports:
            - "3000:3000"
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=admin
            - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
        volumes:
            - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml:ro
        restart: unless-stopped
        depends_on:
            - prometheus
            - loki


    ### --- СЕРВИСЫ ДЛЯ ИНИЦИАЛИЗАЦИИ ---
    schema-initializer:
        image: alpine/curl
        container_name: schema-initializer
        depends_on:
            - kafka
            - schema-registry
        volumes:
            - ./schemas:/schemas
            - ./init-schema.sh:/init-schema.sh
        command: >
            /bin/sh -c "
              apk add --no-cache jq &&
              chmod +x /init-schema.sh &&
              /init-schema.sh
            "
        restart: "no"

    kafka-init:
        image: confluentinc/cp-kafka:8.2.0
        container_name: kafka-init
        depends_on:
            - kafka
        command: >
            sh -c "
              echo 'Create topics...' &&
              kafka-topics --create --if-not-exists --topic devices --replication-factor 1 --partitions 3 --bootstrap-server kafka:9092 &&
              kafka-topics --create --if-not-exists --topic events --replication-factor 1 --partitions 3 --bootstrap-server kafka:9092 &&
              echo 'Done.'
            "
        restart: "no"