spring:
    application:
        name: events.collector

management:
    endpoints:
        web:
            exposure:
                include: health, info, metrics, prometheus
            base-path: /actuator
    endpoint:
        prometheus:
            enabled: true

