springBootVersion=4.0.3
springDependencyManagementVersion=1.1.7

clickHouseJdbc=0.9.8
flywayDatabaseClickhouse=10.24.0

lz4JavaVersion=1.8.1

lombokVersion=9.5.0

mapstructVersion=1.6.3

avroVersion=1.12.1
avroGeneratorPluginVersion=1.9.1
schemaRegistryClientVersion=8.2.1

vavrVersion=1.0.1

dotenvJava=3.0.0